export default {
	"BP_M-Gator_Transport": ["CAF"],
	"BP_M-Gator_Logistics": ["CAF"],
	"BP_M-Gator_Logistics_ARID": ["CAF"],
	"BP_M-Gator_Transport_ARID": ["CAF"],
	"BP_US_Util_Desert": ["USA"],
	"BP_US_Util_Woodland": ["USA"],
	"BP_US_Util_Desert_Logi": ["USA"],
	"BP_US_Util_Woodland_Logi": ["USA"],
	"BP_USMC_Util_Desert": ["USMC"],
	"BP_US_Util_USMC_Woodland": ["USMC"],
	"BP_USMC_Util_Desert_Logi": ["USMC"],
	"BP_US_Util_USMC_Woodland_Logi": ["USMC"],
	"BP_CAF_Util_Desert": ["CAF"],
	"BP_CAF_Util_Woodland": ["CAF"],
	"BP_CAF_Util_Desert_Logi": ["CAF"],
	"BP_CAF_Util_Woodland_Logi": ["CAF"],
	"BP_Brit_Util_Truck": ["BAF"],
	"BP_Brit_Util_Truck_Woodland": ["BAF"],
	"BP_Brit_Util_Truck_Logi": ["BAF"],
	"BP_Brit_Util_Truck_Logi_Woodland": ["BAF"],
	"BP_Aussie_Util_Truck": ["ADF"],
	"BP_Aussie_Util_Truck_Logi": ["ADF"],
	"BP_Ural_375_Desert": ["RGF"],
	"BP_Ural_375_Green": ["RGF"],
	"BP_Ural_375_Mil": ["IMF"],
	"BP_Ural_375_Logi_Mil": ["IMF"],
	"BP_Armored_Ural_375_Logi_Mil": ["IMF"],
	"BP_Ural_375_ZU23_MIL": ["IMF"],
	"BP_Ural_375_INS": ["INS"],
	"BP_Ural_375_Logi_INS": ["INS"],
	"BP_Ural_375_ZU23": ["INS"],
	"BP_Ural_4320_MEA": ["MEA"],
	"BP_Ural_4320_logi_MEA": ["MEA"],
	"BP_Kamaz_5350_Desert": ["RGF", "RAF"],
	"BP_Kamaz_5350": ["RGF", "RAF"],
	"BP_Kamaz_5350_Logi_Desert": ["RGF"],
	"BP_Kamaz_5350_Logi": ["RGF", "RAF"],
	"BP_TLF_Util_Truck_Desert": ["TLF"],
	"BP_TLF_Util_Truck": ["TLF"],
	"BP_TLF_Util_Truck_Logi_Desert": ["TLF"],
	"BP_TLF_Util_Truck_Logi": ["TLF"],
	"BP_CTM131_Desert": ["PLA", "PLAAGF", "PLANMC"],
	"BP_CTM131.BP_CTM131": ["PLA", "PLAAGF", "PLANMC"],
	"BP_CTM131_QJZ89_Desert": ["PLA", "PLAAGF", "PLANMC"],
	"BP_CTM131_QJZ89": ["PLA", "PLAAGF", "PLANMC"],
	"BP_CTM131_Naval": ["PLA", "PLAAGF", "PLANMC"],
	"BP_CTM131_QJZ89_Naval": ["PLA", "PLAAGF", "PLANMC"],
	"BP_CTM131_Logistic_Desert": ["PLA", "PLAAGF", "PLANMC"],
	"BP_CTM131_Logistic": ["PLA", "PLAAGF", "PLANMC"],
	"BP_CTM131_Logistic_Naval": ["PLA", "PLAAGF", "PLANMC"],
	"BP_Technical_Transport_INS": ["INS"],
	"BP_Technical_Logi_INS": ["INS"],
	"BP_Technical_Dshk_INS": ["INS"],
	"BP_Technical_Dshk_Shielded_INS": ["INS"],
	"BP_Technical_Dshk_INS_Armoured": ["INS"],
	"BP_Technical_SPG9_INS": ["INS"],
	"BP_Technical_SPG9_INS_Armoured": ["INS"],
	"BP_Technical_UB32_INS": ["INS"],
	"BP_Technical_Transport_MIL": ["IMF"],
	"BP_Technical_Logi_MIL": ["IMF"],
	"BP_Technical_Dshk_MIL": ["IMF"],
	"BP_Technical_Dshk_Shielded_MIL": ["IMF"],
	"BP_Technical_UB32_MIL": ["IMF"],
	"BP_Technical4Seater_Transport": ["INS"],
	"BP_Technical4Seater_Logi": ["INS"],
	"BP_Technical2Seater_White_M2": ["INS"],
	"BP_Technical2Seater_White_Dshk": ["INS"],
	"BP_Technical2Seater_White_Mortar": ["INS"],
	"BP_Technical2Seater_White_ZU23": ["INS"],
	"BP_Technical2Seater_White_UB32": ["INS"],
	"BP_Technical2Seater_White_BMP1": ["INS"],
	"BP_Technical4Seater_Logi_Camo": ["IMF"],
	"BP_Technical2Seater_Camo_M2": ["IMF"],
	"BP_Technical2Seater_Camo_SPG9": ["IMF"],
	"BP_Technical2Seater_Camo_ZU23": ["IMF"],
	"BP_Technical2Seater_Camo_UB32": ["IMF"],
	"BP_Safir": ["MEA"],
	"BP_Safir_MG3": ["MEA"],
	"BP_Safir_Kord": ["MEA"],
	"BP_Safir_Kornet": ["MEA"],
	"BP_LUVW_Desert": ["CAF"],
	"BP_LUVW": ["CAF"],
	"BP_LUVW_Logi_Desert": ["CAF"],
	"BP_LUVW_Logi": ["CAF"],
	"BP_LUVW_C6_Desert": ["CAF"],
	"BP_LUVW_C6": ["CAF"],
	"BP_LUVW_M2_Desert": ["CAF"],
	"BP_LUVW_M2": ["CAF"],
	"BP_M1151_Technical": ["INS"],
	"BP_M1151_Light": ["USMC"],
	"BP_M1151_Light_Woodland": ["USMC"],
	"BP_M1151": ["USMC"],
	"BP_M1151_Woodland": ["USMC"],
	"BP_M1151_CROWS": ["USMC"],
	"BP_M1151_CROWS_Woodland": ["USMC"],
	"BP_M1151_Mk19": ["USA"],
	"BP_M1151_Light_Mk19": ["USA"],
	"BP_M1151_Mk19_Woodland": ["USA"],
	"BP_M1151_Light_Mk19_Woodland": ["USA"],
	"BP_MATV_M240": ["USA"],
	"BP_MATV_M240_Woodland": ["USA"],
	"BP_MATV": ["USA"],
	"BP_MATV_Woodland": ["USA"],
	"BP_MATV_CROWS_M240": ["USA"],
	"BP_MATV_CROWS_M240_Woodland": ["USA"],
	"BP_MATV_CROWS": ["USA"],
	"BP_MATV_CROWS_Woodland": ["USA"],
	"BP_MATV_TOW": ["USA"],
	"BP_MATV_TOW_Woodland": ["USA"],
	"BP_MATV_USMC": ["USMC"],
	"BP_MATV_USMC_Woodland": ["USMC"],
	"BP_MATV_USMC_CROWS": ["USMC"],
	"BP_MATV_USMC_CROWS_Woodland": ["USMC"],
	"BP_MATV_USMC_TOW": ["USMC"],
	"BP_MATV_USMC_TOW_Woodland": ["USMC"],
	"BP_MATV_Mk19": ["USA"],
	"BP_MATV_Mk19_Woodland": ["USA"],
	"BP_TAPV_C16": ["CAF"],
	"BP_TAPV_C16_Desert": ["CAF"],
	"BP_LPPV": ["BAF"],
	"BP_LPPV_M2RWS": ["BAF"],
	"BP_LPPV_Woodland": ["BAF"],
	"BP_LPPV_M2RWS_Woodland": ["BAF"],
	"BP_PMV_Mag58": ["ADF"],
	"BP_PMV_Mag58x3": ["ADF"],
	"BP_PMV_RWS": ["ADF"],
	"BP_Tigr_Desert": ["RGF"],
	"BP_Tigr": ["RGF", "IMF"],
	"BP_Tigr_RWS_Desert": ["RGF"],
	"BP_Tigr_RWS": ["RGF"],
	"BP_BRDM-2_RUS_Desert": ["RGF"],
	"BP_BRDM-2_RUS": ["RGF"],
	"BP_BRDM-2": ["IMF"],
	"BP_BRDM-2_Insurgents": ["INS"],
	"BP_BRDM-2_MEA": ["MEA"],
	"BP_BRDM-2_Spandrel_RUS_Desert": ["RGF"],
	"BP_BRDM-2_Spandrel_RUS": ["RGF"],
	"BP_BRDM-2_MEA_Spandrel": ["MEA"],
	"BP_BRDM-2_Spandrel": ["IMF"],
	"BP_BRDM-2_Spandrel_INS": ["INS"]
};