{
 "title": "Server Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "SERVER_ID", "label": "Server", "query": "1,2" },
   { "name": "INTERVAL", "label": "Interval", "query": "1m,2m,3m,4m,5m,10m,20m,30m" }
  ]
 },
 "panels": [
  {
   "title": " Only for search in the top scores - This panel does not sort top scores. ",
   "type": "briangann-datatable-panel",
   "description": "This panel does not sort top scores. ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    m.attacker AS \"Steam ID\",\r\n    m.attackerName AS \"Name\",\r\n    `Wounds`,\r\n    `Kills`,\r\n    `Deaths`,\r\n    `Kills`/`Deaths` AS `K/D`,\r\n    `Revives`\r\nFROM `PlayerWounded` m\r\nLEFT JOIN (\r\n    SELECT\r\n           attacker,\r\n           COUNT(*) AS `Wounds`\r\n    FROM `PlayerWounded`\r\n    WHERE\r\n          $__timeFilter(time) AND\r\n          server = $SERVER_ID\r\n    GROUP BY attacker\r\n) w ON w.attacker = m.attacker\r\nLEFT JOIN (\r\n    SELECT\r\n           attacker,\r\n           COUNT(*) AS `Kills`\r\n    FROM `PlayerDied`\r\n    WHERE\r\n          $__timeFilter(time) AND\r\n          server = $SERVER_ID\r\n    GROUP BY attacker\r\n) k ON k.attacker = m.attacker\r\nLEFT JOIN (\r\n    SELECT\r\n           victim,\r\n           COUNT(*) AS `Deaths`\r\n    FROM `PlayerDied`\r\n    WHERE\r\n          $__timeFilter(time) AND\r\n          server = $SERVER_ID\r\n    GROUP BY victim\r\n) d ON d.victim = m.attacker\r\nLEFT JOIN (\r\n    SELECT\r\n           reviver,\r\n           COUNT(*) AS `Revives`\r\n    FROM `PlayerRevived`\r\n    WHERE\r\n          $__timeFilter(time) AND\r\n          server = $SERVER_ID\r\n    GROUP BY reviver\r\n) r ON r.reviver = m.attacker\r\n    WHERE\r\n          $__timeFilter(time) AND\r\n          server = $SERVER_ID \r\nGROUP BY m.attacker\r\nHAVING `K/D` IS NOT NULL;"
    }
   ]
  },
  {
   "title": "Top Scorers",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    m.attacker AS \"Steam ID\",\r\n    m.attackerName AS \"Name\",\r\n    `Wounds`,\r\n    `Kills`,\r\n    `Deaths`,\r\n    `Kills`/`Deaths` AS `K/D`,\r\n    `Revives`\r\nFROM `PlayerWounded` m\r\nLEFT JOIN (\r\n    SELECT\r\n           attacker,\r\n           COUNT(*) AS `Wounds`\r\n    FROM `PlayerWounded`\r\n    WHERE\r\n          $__timeFilter(time) AND\r\n          server = $SERVER_ID\r\n    GROUP BY attacker\r\n) w ON w.attacker = m.attacker\r\nLEFT JOIN (\r\n    SELECT\r\n           attacker,\r\n           COUNT(*) AS `Kills`\r\n    FROM `PlayerDied`\r\n    WHERE\r\n          $__timeFilter(time) AND\r\n          server = $SERVER_ID\r\n    GROUP BY attacker\r\n) k ON k.attacker = m.attacker\r\nLEFT JOIN (\r\n    SELECT\r\n           victim,\r\n           COUNT(*) AS `Deaths`\r\n    FROM `PlayerDied`\r\n    WHERE\r\n          $__timeFilter(time) AND\r\n          server = $SERVER_ID\r\n    GROUP BY victim\r\n) d ON d.victim = m.attacker\r\nLEFT JOIN (\r\n    SELECT\r\n           reviver,\r\n           COUNT(*) AS `Revives`\r\n    FROM `PlayerRevived`\r\n    WHERE\r\n          $__timeFilter(time) AND\r\n          server = $SERVER_ID\r\n    GROUP BY reviver\r\n) r ON r.reviver = m.attacker\r\n    WHERE\r\n          $__timeFilter(time) AND\r\n          server = $SERVER_ID \r\nGROUP BY m.attacker\r\nHAVING `K/D` IS NOT NULL;"
    }
   ]
  },
  {
   "title": "Current Tick Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "tick_rate",
     "query": "SELECT LAST(\"tick_rate\") FROM \"ServerTickRate\" WHERE server = '$SERVER_ID'",
     "rawSql": "SELECT\n  time AS \"time\",\n  tick_rate\nFROM ServerTickRate\nWHERE\n  $__timeFilter(time) AND\n  server = \"$SERVER_ID\"\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Tick Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tick_rate",
     "query": "SELECT \n    mean(\"tick_rate\") \nFROM \"ServerTickRate\" \nWHERE \n    $timeFilter AND\n    server = '$SERVER_ID'\nGROUP BY time($INTERVAL) fill(null)",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(tick_rate) AS \"tick_rate\"\nFROM ServerTickRate\nWHERE\n  $__timeFilter(time) AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Current Player Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "tick_rate",
     "query": "SELECT LAST(\"player_count\") FROM \"PlayerCount\" WHERE server = '$SERVER_ID'",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  player_count AS \"Player Count\"\nFROM PlayerCount\nWHERE\n  $__timeFilter(time) AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval) DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Player Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tick_rate",
     "query": "SELECT \n    MEAN(\"player_count\") \nFROM \"PlayerCount\" \nWHERE \n    $timeFilter AND\n    server = '$SERVER_ID'\nGROUP BY time($INTERVAL) fill(null)",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(player_count) AS \"player_count\"\nFROM PlayerCount\nWHERE\n  $__timeFilter(time) AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Wounded in Time Period",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"victimName\") \nFROM PlayerWounded\nWHERE \n    $timeFilter AND\n    server = '$SERVER_ID'",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"id\"\nFROM PlayerWounded\nWHERE\n  $__timeFilter(time) AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Deaths in Time Period",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n    count(\"victimName\") \nFROM \"PlayerDied\"\nWHERE \n    $timeFilter AND\n     server = '$SERVER_ID'",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"id\"\nFROM PlayerDied\nWHERE\n  $__timeFilter(time) AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "TKs in Time Period",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "player_wound",
     "query": "SELECT \n    count(\"victimName\") \nFROM \"PlayerWounded\"\nWHERE \n    teamkill = true AND\n    $timeFilter AND\n     server = '$SERVER_ID'",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"id\"\nFROM PlayerWounded\nWHERE\n  $__timeFilter(time) AND\n  teamkill = '1' AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Revives in Time Period",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "revive",
     "query": "SELECT count(\"victimName\") FROM \"PlayerRevived\" WHERE $timeFilter AND server = '$SERVER_ID'",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"id\"\nFROM PlayerRevived\nWHERE\n  $__timeFilter(time) AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Recent Teamkills",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\n    a.time AS \"Time\",\n    a.attacker AS \"Attacker\",\n    a.attackerName AS \"Attacker Name\",\n    a.weapon AS \"Weapon\",\n    a.victim AS \"Victim\",\n    a.victimName AS \"Victim Name\",\n    Total AS \"Total in Time Frame\"\nFROM PlayerWounded a\nJOIN\n    (\n      SELECT\n          attacker,\n          COUNT(*) AS \"Total\"\n      FROM PlayerWounded\n      WHERE \n          $__timeFilter(time) AND\n          server = $SERVER_ID AND\n          teamkill = true\n      GROUP BY attacker\n    ) AS b\n    ON a.attacker = b.attacker\nWHERE \n    $__timeFilter(time) AND\n    server = $SERVER_ID AND\n    teamkill = true AND\n    server = $SERVER_ID\nORDER BY time DESC\nLIMIT 30;"
    }
   ]
  },
  {
   "title": "Non-Teamkills vs Teamkills (Wounds)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 56 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Non-Teamkills",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n    COUNT(\"victimName\") \nFROM \"PlayerWounded\" \nWHERE \n    $timeFilter AND\n    server = '$SERVER_ID' AND\n    teamkill = false",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Non-Teamkill\"\nFROM PlayerWounded\nWHERE\n  $__timeFilter(time) AND\n  teamkill = 0 AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "alias": "Teamkills",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n    COUNT(\"victimName\") \nFROM \"PlayerWounded\" \nWHERE \n    $timeFilter AND\n    server = '$SERVER_ID' AND\n    teamkill = true",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Teamkill\"\nFROM PlayerWounded\nWHERE\n  $__timeFilter(time) AND\n  teamkill = '1' AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Wounds Per Minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Players Wounded",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "player_wound",
     "query": "SELECT count(\"victimName\") FROM \"PlayerWounded\" WHERE $timeFilter AND server = '$SERVER_ID' GROUP BY time($INTERVAL) fill(0)",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"All\"\nFROM PlayerWounded\nWHERE\n  $__timeFilter(time) AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "alias": "Players Wounded By Team 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "player_die",
     "query": "SELECT count(\"victimName\") FROM \"PlayerWounded\" WHERE $timeFilter AND server = '$SERVER_ID' AND attackerTeamID=1 GROUP BY time($INTERVAL) fill(0)",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Team 1\"\nFROM PlayerWounded\nWHERE\n  $__timeFilter(time) AND\n  attackerTeamID = 1 AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "alias": "Players Wounded By Team 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "player_die",
     "query": "SELECT count(\"victimName\") FROM \"PlayerWounded\" WHERE $timeFilter AND server = '$SERVER_ID' AND attackerTeamID=2 GROUP BY time($INTERVAL) fill(0)",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Team 2\"\nFROM PlayerWounded\nWHERE\n  $__timeFilter(time) AND\n  attackerTeamID = 2 AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Deaths vs Revives",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 65 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "player_die",
     "query": "SELECT \n    COUNT(\"victimName\") \nFROM \"PlayerDied\" \nWHERE \n    $timeFilter ",
     "rawSql": "SELECT\n  $__timeGroupAlias(woundTime,$__interval),\n  count(id) AS \"Deaths\"\nFROM PlayerDied\nWHERE\n  $__timeFilter(woundTime) AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(woundTime,$__interval)"
    },
    {
     "alias": "Revives",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n    COUNT(\"victimName\") \nFROM \"PlayerRevived\" \nWHERE \n    $timeFilter ",
     "rawSql": "SELECT\n  $__timeGroupAlias(woundTime,$__interval),\n  count(id) AS \"Revives\"\nFROM PlayerRevived\nWHERE\n  $__timeFilter(woundTime) AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(woundTime,$__interval)"
    }
   ]
  },
  {
   "title": "Kills Per Minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Players Killed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "player_wound",
     "query": "SELECT count(\"victimName\") FROM \"PlayerDied\" WHERE $timeFilter AND server = '$SERVER_ID' GROUP BY time($INTERVAL) fill(0)",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"All\"\nFROM PlayerDied\nWHERE\n  $__timeFilter(time) AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "alias": "Players Killed By Team 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "player_die",
     "query": "SELECT count(\"victimName\") FROM \"PlayerDied\" WHERE $timeFilter AND server = '$SERVER_ID' AND attackerTeamID=1 GROUP BY time($INTERVAL) fill(0)",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Team 1\"\nFROM PlayerDied\nWHERE\n  $__timeFilter(time) AND\n  attackerTeamID = 1 AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "alias": "Players Killed By Team 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "player_die",
     "query": "SELECT count(\"victimName\") FROM \"PlayerDied\" WHERE $timeFilter AND server = '$SERVER_ID' AND attackerTeamID=2 GROUP BY time($INTERVAL) fill(0)",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Team 2\"\nFROM PlayerDied\nWHERE\n  $__timeFilter(time) AND\n  attackerTeamID = 2 AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Team 1 vs Team 2",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 74 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Team 1 Kills",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"victimName\") FROM \"PlayerDied\" WHERE $timeFilter AND server = '$SERVER_ID' AND attackerTeamID=1",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Team 1\"\nFROM PlayerWounded\nWHERE\n  $__timeFilter(time) AND\n  attackerTeamID = 1 AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "alias": "Team 2 Kills",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"victimName\") FROM \"PlayerDied\" WHERE $timeFilter AND server = '$SERVER_ID' AND attackerTeamID=2",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Team 2\"\nFROM PlayerWounded\nWHERE\n  $__timeFilter(time) AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Revives Per Minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Revives",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "revive",
     "query": "SELECT count(\"victimName\") FROM \"PlayerRevived\" WHERE $timeFilter AND server = '$SERVER_ID' GROUP BY time($INTERVAL) fill(0)",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"All\"\nFROM PlayerRevived\nWHERE\n  $__timeFilter(time) AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "alias": "Revives",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "revive",
     "query": "SELECT count(\"victimName\") FROM \"PlayerRevived\" WHERE $timeFilter AND server = '$SERVER_ID' AND reviverTeamID = 1 GROUP BY time($INTERVAL) fill(0)",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Team 1\"\nFROM PlayerRevived\nWHERE\n  $__timeFilter(time) AND\n  victimTeamID = 1 AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "alias": "Revives",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "revive",
     "query": "SELECT count(\"victimName\") FROM \"PlayerRevived\" WHERE $timeFilter AND server = '$SERVER_ID' AND reviverTeamID = 2 GROUP BY time($INTERVAL) fill(0)",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Team 2\"\nFROM PlayerRevived\nWHERE\n  $__timeFilter(time) AND\n  victimTeamID = 2 AND\n  server = \"$SERVER_ID\"\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Matches",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "rawSql": "SELECT\n layerClassname as \"Layer\",\n startTime AS \"Start Time\",\n endTime AS \"End Time\"\nFROM `Match`\nWHERE \n    (\n        $__timeFilter(startTime) OR \n        $__timeFilter(endTime) OR\n        endTime IS NULL\n    ) AND \n    server = $SERVER_ID \nORDER BY startTime DESC;"
    }
   ]
  },
  {
   "title": "Layers",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 83 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  layerClassname AS metric,\n  COUNT(*),\n  startTime AS time\nFROM `Match`\nWHERE\n    (\n        $__timeFilter(startTime) OR \n        $__timeFilter(endTime) OR\n        endTime IS NULL\n    ) AND \n    server = $SERVER_ID \nGROUP BY layerClassname"
    }
   ]
  },
  {
   "title": "Maps",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 83 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  mapClassname AS metric,\n  COUNT(*),\n  startTime AS time\nFROM `Match`\nWHERE\n    (\n        $__timeFilter(startTime) OR \n        $__timeFilter(endTime) OR\n        endTime IS NULL\n    ) AND \n    server = $SERVER_ID \nGROUP BY mapClassname"
    }
   ]
  },
  {
   "title": "Weapons",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 91 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Non-Teamkills",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n    COUNT(\"victimName\") \nFROM \"PlayerWounded\" \nWHERE \n    $timeFilter AND\n    server = '$SERVER_ID' AND\n    teamkill = false",
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  weapon AS metric,\n  count(id) AS \"Wounds\"\nFROM PlayerWounded\nWHERE\n  $__timeFilter(time) AND\n  server = \"$SERVER_ID\"\nGROUP BY 2\nORDER BY count(id) DESC"
    }
   ]
  }
 ]
}