const DISCORD_LOGIN_TOKEN = '';

const INFLUXDB_HOST = 'localhost';
const INFLUXDB_PORT = 8086;
const INFLUXDB_USERNAME = 'squadjs';
const INFLUXDB_PASSWORD = 'password';
const INFLUXDB_DATABASE = 'squadjs';
const INFLUXDB_WRITE_INTERVAL = 30 * 1000;

const MYSQL_HOST = 'localhost';
const MYSQL_PORT = 3306;
const MYSQL_USERNAME = 'squadjs';
const MYSQL_PASSWORD = 'password';
const MYSQL_DATABASE = 'squadjs';
const MYSQL_CONNECTION_LIMIT = 10;

export {
  DISCORD_LOGIN_TOKEN,
  INFLUXDB_HOST,
  INFLUXDB_PORT,
  INFLUXDB_USERNAME,
  INFLUXDB_PASSWORD,
  INFLUXDB_DATABASE,
  INFLUXDB_WRITE_INTERVAL,
  MYSQL_HOST,
  MYSQL_PORT,
  MYSQL_USERNAME,
  MYSQL_PASSWORD,
  MYSQL_DATABASE,
  MYSQL_CONNECTION_LIMIT
};
