export default {
  SERVERDATA_EXECCOMMAND: 0x02,
  SERVERDATA_RESPONSE_VALUE: 0x00,

  SERVERDATA_AUTH: 0x03,
  SERVERDATA_AUTH_RESPONSE: 0x02,

  SERVERDATA_CHAT_VALUE: 0x01,

  ID_MID: 0x01,
  ID_END: 0x02
};
